// Keep in sync with Store.Category in backend/stores/models.py.
export const STORE_CATEGORIES = [
  { value: "restaurant", label: "Restaurant" },
  { value: "cafe", label: "Cafe" },
  { value: "coffee_shop", label: "Coffee shop" },
  { value: "bakery", label: "Bakery" },
  { value: "bar", label: "Bar" },
  { value: "meal_takeaway", label: "Meal takeaway" },
  { value: "food_court", label: "Food court" },
  { value: "dessert_shop", label: "Dessert shop" },
  { value: "ice_cream_shop", label: "Ice cream shop" },
  { value: "convenience_store", label: "Convenience store" },
  { value: "supermarket", label: "Supermarket" },
  { value: "grocery_store", label: "Grocery store" },
  { value: "department_store", label: "Department store" },
  { value: "shopping_mall", label: "Shopping mall" },
  { value: "store", label: "Store" },
  { value: "market", label: "Market" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "drugstore", label: "Drugstore" },
  { value: "gas_station", label: "Gas station" },
  { value: "parking", label: "Parking" },
  { value: "hotel", label: "Hotel" },
  { value: "lodging", label: "Lodging" },
  { value: "movie_theater", label: "Movie theater" },
  { value: "beauty_salon", label: "Beauty salon" },
  { value: "hair_salon", label: "Hair salon" },
  { value: "barber_shop", label: "Barber shop" },
  { value: "nail_salon", label: "Nail salon" },
  { value: "laundry", label: "Laundry" },
  { value: "spa", label: "Spa" },
  { value: "gym", label: "Gym" },
]
