# Generated by Django 5.2.17 on 2026-09-08 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_storecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='storecomment',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_comment_user'),
        ),
    ]
