# Generated by Django 5.2.17 on 2026-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
