# Generated by Django 5.2.17 on 2026-09-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_userpoints_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('coffee_shop', 'Coffee shop'), ('bakery', 'Bakery'), ('bar', 'Bar'), ('meal_takeaway', 'Meal takeaway'), ('food_court', 'Food court'), ('dessert_shop', 'Dessert shop'), ('ice_cream_shop', 'Ice cream shop'), ('convenience_store', 'Convenience store'), ('supermarket', 'Supermarket'), ('grocery_store', 'Grocery store'), ('department_store', 'Department store'), ('shopping_mall', 'Shopping mall'), ('store', 'Store'), ('market', 'Market'), ('pharmacy', 'Pharmacy'), ('drugstore', 'Drugstore'), ('gas_station', 'Gas station'), ('parking', 'Parking'), ('hotel', 'Hotel'), ('lodging', 'Lodging'), ('movie_theater', 'Movie theater'), ('beauty_salon', 'Beauty salon'), ('hair_salon', 'Hair salon'), ('barber_shop', 'Barber shop'), ('nail_salon', 'Nail salon'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('gym', 'Gym')], default='', max_length=30),
        ),
    ]
